steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/board-paper-scraper', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/board-paper-scraper']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - run
      - deploy
      - board-paper-scraper
      - --image=gcr.io/$PROJECT_ID/board-paper-scraper
      - --region=europe-west1
      - --memory=2Gi 
      - --timeout=600s
      - --platform=managed
      - --allow-unauthenticated
      - --quiet

images:
  - 'gcr.io/$PROJECT_ID/board-paper-scraper'
