# .github/workflows/ci.yml
name: CI (lint, isort, black, flake8)
on:
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          pip install isort black

      - name: isort check
        run: isort . --check-only

      - name: black check
        run: black . --check
