name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Authenticate to GCP
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3. (Optional) Set up gcloud CLI
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      # 4. Configure Docker so it can push to gcr.io
      - name: Configure Docker credentials
        run: |
          gcloud auth configure-docker --quiet

      # 5. Build & push the Docker image
      - name: Build & push Docker image
        run: |
          docker build \
            --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/board-paper-scraper:latest \
            .
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/board-paper-scraper:latest

      # 6. Deploy the image to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy board-paper-scraper \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/board-paper-scraper:latest \
            --region europe-west1 \
            --platform managed \
            --memory=2Gi \
            --timeout=600s \
            --allow-unauthenticated
